# Generated by Django 5.2.8 on 2025-11-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(unique=True, verbose_name='Kun raqami')),
                ('title', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('description', models.TextField(verbose_name='Vazifa tavsifi')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Bajarildimi?')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Kunlik xulosa/qaydlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
