# Generated by Django 5.2.8 on 2025-11-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dailyplan',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='difficulty',
            field=models.CharField(choices=[('easy', '🟢 Oson'), ('medium', "🟡 O'rta"), ('hard', '🔴 Qiyin')], default='medium', max_length=10, verbose_name='Qiyinlik'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='resource_url',
            field=models.URLField(blank=True, null=True, verbose_name="Qo'shimcha Material"),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Kutilmoqda'), ('in_progress', '🔥 Jarayonda'), ('completed', '✅ Tugatildi')], default='pending', max_length=20, verbose_name='Holat'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='time_spent',
            field=models.FloatField(default=0, verbose_name='Sarflangan soat'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video Darslik Linki'),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='description',
            field=models.TextField(verbose_name='Batafsil tavsif'),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Kunlik xulosa'),
        ),
    ]
